#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.
waccFile = ARGV[0]
system("java -cp bin:lib/antlr-4.4-complete.jar antlr.WACCCompiler #{waccFile}")
puts "Exit Status" + $?.to_s
exit($?.exitstatus)
