#!/usr/bin/ruby
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: execute [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
end.parse!

fileName = ARGV[0]
if (!fileName)
	abort("You must provide a file")
end

basename = File.basename(fileName, ".wacc");
assemblyName = "#{basename}.s"

puts "=" * 50
puts "Compiling code"
system("./compile #{fileName}")
if (options[:verbose])
  system("cat #{assemblyName}")
end

puts "=" * 50
puts "Assembling code"
system("arm-linux-gnueabi-gcc -o #{basename}  -mcpu=arm1176jzf-s -mtune=arm1176jzf-s #{assemblyName}")

puts "=" * 50
puts "Executing code"
system("qemu-arm -L /usr/arm-linux-gnueabi/ #{basename}")

exitCode = $?.exitstatus
puts "=" * 50
puts "Exit code:"  
puts exitCode

`rm #{basename} #{assemblyName}`
