#!/usr/bin/ruby
def finish ()
	`rm testResult.txt`
	exit!
end

def recursiveTest (directory)
	allFiles = Dir.entries(directory)
	allFiles.delete(".")
	allFiles.delete("..")

	allFiles.each do |waccFile|
		waccFilePath = directory + waccFile
		if(File.extname(waccFilePath) == ".wacc")
			testFile(waccFilePath)
		elsif (File.directory?(waccFilePath))
			recursiveTest(waccFilePath + '/')
		else
			puts "[INFO] Ignoring file #{waccFilePath}"
		end
	end
end

def testFile (waccFilePath)
	puts "[INFO] Running file #{waccFilePath}" 
	`./grun WACC prog #{waccFilePath} 2> testResult.txt`
	resultLength = `wc -l testResult.txt`.scan(/[0-9]+/)[0].to_i
	if(resultLength > 0)
		puts "[ERROR] FAILURE AT #{waccFilePath}, running on gui: "
		`open #{waccFilePath}`
		`./grun WACC prog -gui #{waccFilePath}`
		finish()
	end
end

arg0 = ARGV[0]

if (arg0 == nil)
	recursiveTest(".")
elsif (File.directory?(arg0))
	recursiveTest(arg0)
elsif (File.extname(arg0) == ".wacc")
	testFile(arg0)
else
	puts "testAll: Invalid arguments provided"
end