#!/bin/sh

LEXER_FILE=JSTypeLexer.g4
PARSER_FILE=JSTypeParser.g4

BASEDIR=$(dirname $0)

TARGET_DIR=./build
PACKAGE=jsparser.build

rm -rf $TARGET_DIR

echo Compiling the lexer..
java -jar $BASEDIR/../../../lib/antlr-4.4-complete.jar $BASEDIR/$LEXER_FILE -o $TARGET_DIR -no-listener -visitor -Werror -package $PACKAGE

if [ $? -ne 0 ]
then 
	exit 1
fi

echo Compiling the parser..
java -jar $BASEDIR/../../../lib/antlr-4.4-complete.jar $BASEDIR/$PARSER_FILE -o $TARGET_DIR -no-listener -visitor -Werror -package $PACKAGE
